DROP TABLE IF EXISTS COURSE_WORK;
CREATE SCHEMA ASSIGNMENT AUTHORIZATION SA;

CREATE TABLE ASSIGNMENT.COURSE_WORK (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  Assignment_Name VARCHAR(250) NOT NULL,
  Assignment_Desc VARCHAR(1000) NOT NULL,
  Updated_At DATE DEFAULT NULL,
  Updated_By VARCHAR(10) NOT NULL
);